# espanso configuration file

# packages
# espanso install shruggie
# espanso install lorem

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"

  # Personal
  - trigger: ":email"
    replace: "jonas.elan@gmail.com"
    
